/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

/**
 *
 * @author sandaime
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background2 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblUsuario = new javax.swing.JLabel();
        jlblPass = new javax.swing.JLabel();
        jbtnEnter = new javax.swing.JButton();
        jtxtUser = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jbtnEnter1 = new javax.swing.JButton();
        jbtnEnter2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(12, 138, 199));
        setForeground(new java.awt.Color(12, 138, 199));
        setIconImages(null);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background2.setBackground(new java.awt.Color(12, 138, 199));
        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hotel2.png"))); // NOI18N
        getContentPane().add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 0, 280, 450));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aH-40px.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 40));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(12, 138, 199));
        jLabel4.setText("INICIAR DE SESIÓN");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jlblUsuario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jlblUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jlblUsuario.setText("USUARIO");
        getContentPane().add(jlblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jlblPass.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jlblPass.setForeground(new java.awt.Color(102, 102, 102));
        jlblPass.setText("CONTRASEÑA");
        getContentPane().add(jlblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jbtnEnter.setBackground(new java.awt.Color(12, 138, 199));
        jbtnEnter.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jbtnEnter.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEnter.setText("ENTER");
        jbtnEnter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jbtnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 365, 130, 50));

        jtxtUser.setForeground(new java.awt.Color(153, 153, 153));
        jtxtUser.setText(" Ingrese su nombre de usuario");
        jtxtUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 138, 199), 2));
        getContentPane().add(jtxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 310, -1));

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 138, 199), 2));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 310, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(12, 138, 199));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VOLVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 365, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 450));

        jbtnEnter1.setBackground(new java.awt.Color(12, 138, 199));
        jbtnEnter1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jbtnEnter1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEnter1.setText("ENTER");
        jbtnEnter1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jbtnEnter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 365, 130, 50));

        jbtnEnter2.setBackground(new java.awt.Color(12, 138, 199));
        jbtnEnter2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jbtnEnter2.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEnter2.setText("ENTER");
        jbtnEnter2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jbtnEnter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 365, 130, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Manager go=new Manager();
        go.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background2;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton jbtnEnter;
    private javax.swing.JButton jbtnEnter1;
    private javax.swing.JButton jbtnEnter2;
    private javax.swing.JLabel jlblPass;
    private javax.swing.JLabel jlblUsuario;
    private javax.swing.JTextField jtxtUser;
    // End of variables declaration//GEN-END:variables
}
